apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-nzjalbgu
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-nzjalbgu:12ec5a9f3757b64eed74571392c9dfbfb0ca367d@sha256:0648532f155c38dfd226e02a005c51ed0fc5672498cbbab65b7aff2cede20e47
          name: container-image
